on:
  push:
    # tags:
    #   - "v*"
    branches:
      - github-actions

name: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set outputs
        id: vars
        run: echo ::set-output name=release_file_name::flo-release-${GITHUB_REF##*/}-${{ runner.os }}.zip
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build flo-ping
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p flo-ping

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{ steps.vars.outputs.release_file_name }}
          directory: target/release
          exclusions: '.* build deps examples incremental *.pdb *.d *.rlib'

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: test
          files: |
            target/release/*.zip