on:
  push:
    # tags:
    #   - "v*"
    branches:
      - github-actions

name: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      FLO_RELEASE_FILE_NAME: "flo-release-${GITHUB_REF##*/}-${{ env.RUNNER_OS }}.zip"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build flo-ping
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release -p flo-ping

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{ env.FLO_RELEASE_FILE_NAME }}
          directory: target/release

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/release/*